### ISSUE TITLE
Remove unnecessary code from _variables.scss

### ISSUE THREAD

**Issue by tdharmon** [m-spyratos/bootstrap-4-grid#4]
I'm using this project to add support for basic grid and positioning utilities from bootstrap without having bootstrap take over my entire project. I wanted to use the breakpoint mixins provided by bootstrap (imported from this project), but I found that, in order to do so, I have to import the variables file, which still has all of the variables from bootstrap. 

Is there a reason why all of the variables are still part of the file? I want to remove them (I've forked this repo, and I'll make a PR), but I wanted to ask first, to see if there was a reason why they're still included.

I also was curious why there was file duplication? There are multiple copies of `_display` and `_visibility`.

**Comment by m-spyratos** [comment]
@tdharmon I haven't manipulated the core bootstrap files to fit my needs, because I want to be able to easily upgrade to the latest versions. Also, it doesn't seem to be a concern, as what you don't use won't get compiled.

The same goes with the duplicated files. I do it to keep a separation of concerns for an easy upgrade and to enable/disable features if needed. This shouldn't affect your compiled project though.

**Comment by tdharmon** [comment]
@m-spyratos I went back and revisited this and couldn't reproduce the errors I was originally seeing 🤔  I was originally seeing errors while importing `_variables`.

SASS doesn't let you import references like LESS does, so importing _all_ the variables seems a little bit gross to me, but I get that it makes it easier to maintain.
